version: 2
multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: weekly
      day: saturday
      time: 02:00
      timezone: Australia/Brisbane
updates:
- package-ecosystem: cargo
  directory: /
  patterns:
  - '*'
  multi-ecosystem-group: dependencies
  groups:
    cargo:
      patterns:
      - '*'
- package-ecosystem: cargo
  directory: /tools/repair-pnpm-lockfile
  patterns:
  - '*'
  multi-ecosystem-group: dependencies
  groups:
    cargo:
      patterns:
      - '*'
- package-ecosystem: npm
  directory: /
  patterns:
  - '*'
  multi-ecosystem-group: dependencies
  groups:
    npm:
      patterns:
      - '*'
- package-ecosystem: github-actions
  directory: /
  patterns:
  - '*'
  multi-ecosystem-group: dependencies
  groups:
    github-actions:
      patterns:
      - '*'
