[package]
name = "websites"
version = "0.1.0"
edition = "2024"

default-run = "websites"

[lib]

[dependencies]
anyhow = "1.0.102"
askama = "0.15.4"
askama_web = { version = "0.15.2", features = ["axum-0.8", "tracing-0.1"] }
axum = { version = "0.8.8", features = ["multipart", "macros"] }
axum-server = { version = "0.8.0", features = ["tokio-rustls", "tls-rustls"] }
chrono = "0.4.44"
clap = { version = "4.6.0", features = ["derive", "env"] }
compact_jwt = "0.5.5"
gix = { version = "0.81.0", default-features = false, features = [
    "blocking-http-transport-reqwest",
    "blocking-http-transport-reqwest-rust-tls",
    "blocking-network-client",
    "sha1",
    "worktree-mutation",
] }
glob = "0.3.3"
image = "0.25.10"
markdown = "1.0.0"
mime_guess = "2.0.5"
openidconnect = { version = "4.0.1", features = ["reqwest"] }
quick-xml = "0.39.2"
rand = "0.10.0"
regex = "1.12.3"
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "json",
] }
rustls = "0.23.37"
sea-orm = { version = "1.1.19", features = [
    "runtime-tokio-rustls",
    "sqlx-sqlite",
    "with-chrono",
    "with-json",
    "with-uuid",
], default-features = false }
sea-orm-migration = { version = "1.1.19", default-features = false, features = [
    "runtime-tokio-rustls",
    "sqlx-sqlite",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
similar = "2.7.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "sqlite"] }
tempfile = "3.27.0"
tera = "1.20.1"
tokio = { version = "1.50.0", features = [
    "rt-multi-thread",
    "macros",
    "signal",
] }
tower-http = { version = "0.6.8", features = ["fs"] }
tower-sessions = "0.15.0"
tower-sessions-sqlx-store = { version = "0.15.0", features = ["sqlite"] }
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.23", features = [
    "json",
    "serde",
    "tracing",
    "env-filter",
] }
url = "2.5.8"
utoipa = { version = "5.4.0", features = [
    "url",
    "uuid",
    "time",
    "chrono",
    "axum_extras",
] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "vendored"] }
uuid = { version = "1.22.0", features = ["v7"] }

[dev-dependencies]
tempfile = "3.27.0"
tower = "0.5.2"
