[tools]
pnpm = "latest"

[tasks.check]
depends = ["rust_clippy", "rust_fmt", "rust_test", "frontend_check"]


[tasks.rust_clippy]
run = "cargo clippy --all-targets --all-features  --quiet -- -D warnings"

[tasks.rust_fmt]
run = "cargo fmt --all --"

[tasks.rust_test]
run = "cargo test --all --quiet"

[tasks.frontend_build]
run = "pnpm run build:admin"

[tasks.frontend_check]
run = "pnpm install --frozen-lockfile && pnpm exec tsc --noEmit"

[tasks.start]
depends = ["frontend_build"]
run = "cargo run"
