/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/site/{site_id}/assets/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_site_assets_library"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssetLibraryItem: {
            created_at: string;
            has_thumbnail: boolean;
            /** Format: int32 */
            height?: number | null;
            /** Format: uuid */
            id: string;
            mime_type: string;
            original_filename: string;
            original_url: string;
            thumbnail_url?: string | null;
            /** Format: int32 */
            width?: number | null;
        };
        AssetLibraryResponse: {
            assets: components["schemas"]["AssetLibraryItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_site_assets_library: {
        parameters: {
            query: {
                /** @description Optional search query to filter assets by original filename or storage basename */
                q: string;
                /** @description Optional filter by image type (jpeg, png, gif, svg, webp) */
                type: string;
            };
            header?: never;
            path: {
                /** @description The ID of the site to list assets for */
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of assets matching the query */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetLibraryResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Unauthorized access */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Forbidden - insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
export enum ApiPaths {
    api_site_assets_library = "/api/site/{site_id}/assets/library"
}
