---
name: Build Container

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  build_container:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      platforms: linux/amd64,linux/arm64
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      distribute: true
      setup-qemu: false
      cache: true
      cache-mode: max
      cache-scope: websites-container
      context: .
      file: ./Dockerfile
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=sha,prefix=sha-
        type=raw,value=latest
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
