---
name: Semgrep checks

"on":
  pull_request:
  push:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install mise
        uses: jdx/mise-action@v4
      - name: Run semgrep
        run: mise run semgrep
